<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-06-26 10:47
=======
# Generated by Django 4.2.2 on 2023-06-26 09:53
>>>>>>> main

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Student',
=======
            name='student',
>>>>>>> main
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('d', 'diverse')], max_length=1)),
                ('birth_date', models.DateTimeField()),
                ('grade', models.CharField(choices=[('a', 'Associate degree (undergraduate)'), ('b', "Bachelor's degree (undergraduate)"), ('m', "Master's degree (graduate)"), ('d', 'Doctoral degree (graduate)')], max_length=1)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('graduation_date', models.DateTimeField()),
                ('address', models.TextField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
    ]
