# Generated by Django 4.2.2 on 2023-06-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('Associate', 'Associate degree (undergraduate)'), ('Bachelor', "Bachelor's degree (undergraduate)"), ('Master', "Master's degree (graduate)"), ('Doctoral', 'Doctoral degree (graduate)')], max_length=9),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('diverse', 'diverse')], max_length=7),
        ),
    ]
