# Generated by Django 4.2.2 on 2023-06-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_grade_alter_student_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='register_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
