# Generated by Django 4.2.2 on 2023-07-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='register_date',
            field=models.DateField(),
        ),
    ]
